version: "3"
services:
  database:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
  api:
    container_name: peavote_api
    build: ./api
    links:
      - database
    depends_on:
      - database
    restart: unless-stopped
    expose:
      - 8080
    ports:
      - 8080:3001
    environment:
      - DATABASE_URI=postgres://docker:docker@database:5432/docker
  frontend:
    container_name: peavote_frontend
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - REACT_URI=http://localhost:8080
